import {APP_WIDTH,APP_HEIGHT} from '../constants/constant';

export const BASIC_TEXT_VIEW_HEIGHT = APP_HEIGHT*3/40;
export const BASIC_FONT_SIZE = BASIC_TEXT_VIEW_HEIGHT*1/2;
export const LOCATION_NAME_FONT_SIZE = BASIC_TEXT_VIEW_HEIGHT*1/2;

export const FORECAST_CONTAINER_WIDTH = APP_WIDTH*1/2;
export const FORECAST_CONTAINER_HEIGHT = APP_HEIGHT*3/7;

export const FORECAST_TEMPERATURE_CONTAINER_HEIGHT = FORECAST_CONTAINER_HEIGHT*3/5;
export const FORECAST_TEMPERATURE_FONT_SIZE = FORECAST_TEMPERATURE_CONTAINER_HEIGHT*1/4;

export const FORECAST_INFO_CONTAINER_HEIGHT = FORECAST_CONTAINER_HEIGHT*1/10;
export const FORECAST_INFO_FONT_SIZE = FORECAST_INFO_CONTAINER_HEIGHT*1/3;